spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
    initialSize: 1
    maxActive: 5
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:logback-conf.xml

swagger:
  enable: true
